---
title: "TOPC Cohort 3 Analysis"
subtitle: "Pre-test"
author: "Elham Ali"
date: Dec 20, 2023
format:
  html:
    toc: true
    code-fold: true
    code-summary: "Show the code"
editor: visual
cache: true
---

Graphs for pre-test survey analysis for city governments.

## Install necessary packages

```{r}
#| label: packages-installation
#| message: false

# Set a CRAN mirror
options(repos = c(CRAN = "https://cloud.r-project.org"))

# Install necessary packages
# install.packages("magrittr")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("knitr")
# install.packages("KableExtra")
# install.packages("survey")

# Load the packages
library(magrittr)
library(dplyr)
library(ggplot2)
library(knitr)
library(survey)
```

## Calculate design weights

```{r}
#| label: design-weights
#| message: false

# Read the data from the CSV file
cohort3BackgroundGov <- read.csv("~/Documents/GitHub/TOPC-impact-evaluation-dashboard/Cohort 3/cohort3BackgroundGov2.csv")

# Define population and sample sizes
population_counts <- c(Akron = 8, Detroit = 9, Macon = 10, Miami = 13)
sample_counts <- c(Akron = 4, Detroit = 2, Macon = 4, Miami = 3)

# Total population and sample size
total_population <- sum(population_counts)
total_sample <- sum(sample_counts)

# Calculate the weights
weights <- (population_counts / total_population) / (sample_counts / total_sample)

# Print the calculated weights
print(weights)
```

## Define the survey design

```{r}
{r}
#| label: survey-design-definition
#| message: false
# Map between city names 
city_map <- list(
  "Miami-Dade County, FL" = "Miami",
  "Akron, OH" = "Akron",
  "Detroit, MI" = "Detroit",
  "Macon-Bibb County, GA" = "Macon"
)

# Update dataframe to use the mapped names
cohort3BackgroundGov$city_mapped <- unlist(lapply(cohort3BackgroundGov$q3, function(x) city_map[[x]]))

# Assign weights using the mapped city names
cohort3BackgroundGov$weights <- weights[cohort3BackgroundGov$city_mapped]

# Define the survey design
design <- svydesign(ids = ~1, 
                    strata = ~city_mapped, 
                    weights = ~weights, 
                    data = cohort3BackgroundGov)
```
